name: Lint check
on:
  pull_request:
    paths:
      - 'factorial.py'
jobs:
  job1:
    name: Strict lint check
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - run: echo "Running strict lint check..."
      - run: echo "Strict lint quality is optional for project build and delivery"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run linter
        run: python lint_test_strict.py
  job2:
    name: Loose lint check
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running loose lint check..."
      - run: echo "This lint check is mandatory"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
      - name: Run linter
        run: python lint_test.py
  job3:
    name: Build
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "Building solution..."
        sleep 10
        echo "Build complete"