name: Lint and Style Check
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This has been triggered ${{ github.event_name }} event"
      - run: echo "This job is running on ${{ runner.os }} container"
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint
          pip install pycodestyle
      - name: Run linter
        run: python lint_test.py
      - name: Style with pycodestyle
        run: |
          pycodestyle *.py
      - name: Unit testing
        run: |
          python3 -m doctest factorial.py
      - name: Build container
        run: |
          echo "Building a container image..."
          sleep 10
      - name: Deploy to cluster
        run: |
          echo "Deploying to cluster"
          sleep 10
          echo "Container has deployed"
      - run: echo "This job's status is ${{ job.status }}."
